# Generated by Django 2.2.1 on 2022-08-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190511_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
