# Generated by Django 2.2.1 on 2022-08-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220804_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
