# Generated by Django 2.2.1 on 2022-08-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20220804_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
