# Generated by Django 2.2.1 on 2022-08-04 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20220804_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
