# Generated by Django 2.2.1 on 2022-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20220804_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
